# Generated by Django 5.2.13 on 2026-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
                ('category_of_film', models.PositiveIntegerField(choices=[(1, 'Horror'), (2, 'Action'), (3, 'Adventure'), (4, 'Animation'), (5, 'Comedy'), (6, 'Crime'), (7, 'Drama')], verbose_name='category_of_film')),
            ],
        ),
    ]
